import * as bcrypt from "bcrypt";

import {
  LedgerCategory,
  LedgerType,
  Prisma,
  PrismaClient,
} from "@prisma/client";

const prisma = new PrismaClient();

const SEEDED_OWNED_POOR_ITEM_CODES = [
  "clothes-07",
  "pants-04",
  "accessory-01",
  "shoes-07",
  "clothes-08",
] as const;

const SEEDED_EQUIPPED_POOR_ITEM_CODES = new Set<string>([
  "clothes-07",
  "pants-04",
  "accessory-01",
  "shoes-07",
]);

type SeedItem = {
  name: string;
  type: LedgerType;
  category: LedgerCategory;
  amount: number;
  date: string;
};

const seedData: SeedItem[] = [
  // 2026-01
  {
    name: "월급",
    type: "income",
    category: "salary",
    amount: 3200000,
    date: "2026-01-02",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -12000,
    date: "2026-01-02",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -5900,
    date: "2026-01-03",
  },
  {
    name: "교통비",
    type: "expense",
    category: "transport",
    amount: -2800,
    date: "2026-01-03",
  },
  {
    name: "마트",
    type: "expense",
    category: "living",
    amount: -42800,
    date: "2026-01-05",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -13000,
    date: "2026-01-08",
  },
  {
    name: "저녁",
    type: "expense",
    category: "food",
    amount: -21000,
    date: "2026-01-08",
  },
  {
    name: "생활용품",
    type: "expense",
    category: "living",
    amount: -18300,
    date: "2026-01-10",
  },
  {
    name: "병원",
    type: "expense",
    category: "health",
    amount: -24000,
    date: "2026-01-12",
  },
  {
    name: "용돈",
    type: "income",
    category: "gift",
    amount: 50000,
    date: "2026-01-15",
  },
  {
    name: "외식",
    type: "expense",
    category: "food",
    amount: -36000,
    date: "2026-01-15",
  },
  {
    name: "온라인 쇼핑",
    type: "expense",
    category: "shopping",
    amount: -51900,
    date: "2026-01-18",
  },
  {
    name: "보너스",
    type: "income",
    category: "bonus",
    amount: 120000,
    date: "2026-01-20",
  },
  {
    name: "버스",
    type: "expense",
    category: "transport",
    amount: -1500,
    date: "2026-01-22",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -11500,
    date: "2026-01-22",
  },
  {
    name: "중고 판매",
    type: "income",
    category: "etc",
    amount: 22000,
    date: "2026-01-25",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -6200,
    date: "2026-01-28",
  },
  {
    name: "간식",
    type: "expense",
    category: "food",
    amount: -4800,
    date: "2026-01-28",
  },
  {
    name: "문화생활",
    type: "expense",
    category: "culture",
    amount: -18000,
    date: "2026-01-30",
  },

  // 2026-02
  {
    name: "월급",
    type: "income",
    category: "salary",
    amount: 3200000,
    date: "2026-02-02",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -12500,
    date: "2026-02-02",
  },
  {
    name: "교통비",
    type: "expense",
    category: "transport",
    amount: -2800,
    date: "2026-02-03",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -5700,
    date: "2026-02-03",
  },
  {
    name: "마트",
    type: "expense",
    category: "living",
    amount: -39200,
    date: "2026-02-05",
  },
  {
    name: "저녁",
    type: "expense",
    category: "food",
    amount: -22000,
    date: "2026-02-07",
  },
  {
    name: "생활용품",
    type: "expense",
    category: "living",
    amount: -15400,
    date: "2026-02-10",
  },
  {
    name: "병원",
    type: "expense",
    category: "health",
    amount: -18000,
    date: "2026-02-12",
  },
  {
    name: "외식",
    type: "expense",
    category: "food",
    amount: -31000,
    date: "2026-02-14",
  },
  {
    name: "용돈",
    type: "income",
    category: "gift",
    amount: 30000,
    date: "2026-02-16",
  },
  {
    name: "온라인 쇼핑",
    type: "expense",
    category: "shopping",
    amount: -47800,
    date: "2026-02-18",
  },
  {
    name: "보너스",
    type: "income",
    category: "bonus",
    amount: 150000,
    date: "2026-02-20",
  },
  {
    name: "버스",
    type: "expense",
    category: "transport",
    amount: -1500,
    date: "2026-02-22",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -11800,
    date: "2026-02-22",
  },
  {
    name: "중고 판매",
    type: "income",
    category: "etc",
    amount: 18000,
    date: "2026-02-24",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -6100,
    date: "2026-02-26",
  },
  {
    name: "간식",
    type: "expense",
    category: "food",
    amount: -4200,
    date: "2026-02-26",
  },
  {
    name: "쇼핑",
    type: "expense",
    category: "shopping",
    amount: -38900,
    date: "2026-02-28",
  },

  // 2026-03
  {
    name: "월급",
    type: "income",
    category: "salary",
    amount: 3200000,
    date: "2026-03-02",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -13000,
    date: "2026-03-02",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -6500,
    date: "2026-03-03",
  },
  {
    name: "교통비",
    type: "expense",
    category: "transport",
    amount: -2800,
    date: "2026-03-03",
  },
  {
    name: "마트",
    type: "expense",
    category: "living",
    amount: -46800,
    date: "2026-03-05",
  },
  {
    name: "병원",
    type: "expense",
    category: "health",
    amount: -27000,
    date: "2026-03-08",
  },
  {
    name: "생활용품",
    type: "expense",
    category: "living",
    amount: -21200,
    date: "2026-03-10",
  },
  {
    name: "외식",
    type: "expense",
    category: "food",
    amount: -42000,
    date: "2026-03-14",
  },
  {
    name: "디저트",
    type: "expense",
    category: "cafe",
    amount: -9800,
    date: "2026-03-14",
  },
  {
    name: "용돈",
    type: "income",
    category: "gift",
    amount: 70000,
    date: "2026-03-16",
  },
  {
    name: "온라인 쇼핑",
    type: "expense",
    category: "shopping",
    amount: -83200,
    date: "2026-03-18",
  },
  {
    name: "중고 판매",
    type: "income",
    category: "etc",
    amount: 35000,
    date: "2026-03-20",
  },
  {
    name: "버스",
    type: "expense",
    category: "transport",
    amount: -1500,
    date: "2026-03-22",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -12000,
    date: "2026-03-22",
  },
  {
    name: "문화생활",
    type: "expense",
    category: "culture",
    amount: -25000,
    date: "2026-03-25",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -5900,
    date: "2026-03-27",
  },
  {
    name: "간식",
    type: "expense",
    category: "food",
    amount: -4500,
    date: "2026-03-27",
  },
  {
    name: "보너스",
    type: "income",
    category: "bonus",
    amount: 100000,
    date: "2026-03-30",
  },

  // 2026-04
  {
    name: "월급",
    type: "income",
    category: "salary",
    amount: 3200000,
    date: "2026-04-02",
  },
  {
    name: "점심",
    type: "expense",
    category: "food",
    amount: -11000,
    date: "2026-04-02",
  },
  {
    name: "교통비",
    type: "expense",
    category: "transport",
    amount: -3200,
    date: "2026-04-04",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -5800,
    date: "2026-04-04",
  },
  {
    name: "마트",
    type: "expense",
    category: "living",
    amount: -35100,
    date: "2026-04-06",
  },
  {
    name: "약국",
    type: "expense",
    category: "health",
    amount: -9800,
    date: "2026-04-09",
  },
  {
    name: "브런치",
    type: "expense",
    category: "food",
    amount: -28000,
    date: "2026-04-12",
  },
  {
    name: "용돈",
    type: "income",
    category: "gift",
    amount: 50000,
    date: "2026-04-15",
  },
  {
    name: "생활용품",
    type: "expense",
    category: "living",
    amount: -16400,
    date: "2026-04-15",
  },
  {
    name: "쇼핑",
    type: "expense",
    category: "shopping",
    amount: -42900,
    date: "2026-04-18",
  },
  {
    name: "중고 판매",
    type: "income",
    category: "etc",
    amount: 28000,
    date: "2026-04-20",
  },
  {
    name: "버스",
    type: "expense",
    category: "transport",
    amount: -1500,
    date: "2026-04-22",
  },
  {
    name: "저녁",
    type: "expense",
    category: "food",
    amount: -19000,
    date: "2026-04-22",
  },
  {
    name: "카페",
    type: "expense",
    category: "cafe",
    amount: -6300,
    date: "2026-04-24",
  },
  {
    name: "문화생활",
    type: "expense",
    category: "culture",
    amount: -18000,
    date: "2026-04-27",
  },
  {
    name: "보너스",
    type: "income",
    category: "bonus",
    amount: 80000,
    date: "2026-04-29",
  },
];

const poorItems: Prisma.PoorItemCreateManyInput[] = [
  {
    code: "clothes-01",
    name: "축축한 종이박스",
    category: "clothes",
    price: 20,
    requiredLevel: 1,
    imgUrl: "/images/poor-items/clothes/clothes-01.svg",
    sortOrder: 1,
    isActive: true,
  },
  {
    code: "clothes-02",
    name: "꼬질꼬질 홀터넥",
    category: "clothes",
    price: 20,
    requiredLevel: 2,
    imgUrl: "/images/poor-items/clothes/clothes-02.svg",
    sortOrder: 2,
    isActive: true,
  },
  {
    code: "clothes-03",
    name: "꼬질꼬질 난닝구",
    category: "clothes",
    price: 20,
    requiredLevel: 3,
    imgUrl: "/images/poor-items/clothes/clothes-03.svg",
    sortOrder: 3,
    isActive: true,
  },
  {
    code: "clothes-04",
    name: "구찌..아니 아구찜",
    category: "clothes",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/clothes/clothes-04.svg",
    sortOrder: 4,
    isActive: true,
  },
  {
    code: "clothes-05",
    name: "늘어난 반팔",
    category: "clothes",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/clothes/clothes-05.svg",
    sortOrder: 5,
    isActive: true,
  },
  {
    code: "clothes-06",
    name: "의류수거함 카라티",
    category: "clothes",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/clothes/clothes-06.svg",
    sortOrder: 6,
    isActive: true,
  },
  {
    code: "clothes-07",
    name: "거지의 첫 셔츠",
    category: "clothes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-07.svg",
    sortOrder: 7,
    isActive: true,
  },
  {
    code: "clothes-08",
    name: "거지의 소개팅 셔츠",
    category: "clothes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-08.svg",
    sortOrder: 8,
    isActive: true,
  },
  {
    code: "clothes-09",
    name: "시장에서 산 맨투맨",
    category: "clothes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-09.svg",
    sortOrder: 9,
    isActive: true,
  },
  {
    code: "clothes-10",
    name: "스마일 맨투맨",
    category: "clothes",
    price: 20,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-10.svg",
    sortOrder: 10,
    isActive: true,
  },
  {
    code: "clothes-11",
    name: "아보카도 맨투맨",
    category: "clothes",
    price: 20,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-11.svg",
    sortOrder: 11,
    isActive: true,
  },
  {
    code: "clothes-12",
    name: "노랑 맨투맨",
    category: "clothes",
    price: 20,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/clothes/clothes-12.svg",
    sortOrder: 12,
    isActive: true,
  },
  {
    code: "clothes-13",
    name: "반팔 웨이터 유니폼 - 블랙",
    category: "clothes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/clothes/clothes-13.svg",
    sortOrder: 13,
    isActive: true,
  },
  {
    code: "clothes-14",
    name: "반팔 웨이터 유니폼 - 베이지",
    category: "clothes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/clothes/clothes-14.svg",
    sortOrder: 14,
    isActive: true,
  },
  {
    code: "clothes-15",
    name: "블레이저 - 블랙",
    category: "clothes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/clothes/clothes-15.svg",
    sortOrder: 15,
    isActive: true,
  },
  {
    code: "clothes-16",
    name: "블레이저 - 베이지",
    category: "clothes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/clothes/clothes-16.svg",
    sortOrder: 16,
    isActive: true,
  },
  // 하의
  {
    code: "pants-01",
    name: "길에서 주운 청 반바지",
    category: "pants",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/pants/pants-01.svg",
    sortOrder: 1,
    isActive: true,
  },
  {
    code: "pants-02",
    name: "길에서 주운 면 반바지",
    category: "pants",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/pants/pants-02.svg",
    sortOrder: 2,
    isActive: true,
  },
  {
    code: "pants-03",
    name: "물새는 수영복 바지",
    category: "pants",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/pants/pants-03.svg",
    sortOrder: 3,
    isActive: true,
  },
  {
    code: "pants-04",
    name: "검은 면바지",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-04.svg",
    sortOrder: 4,
    isActive: true,
  },
  {
    code: "pants-05",
    name: "남색 면바지",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-05.svg",
    sortOrder: 5,
    isActive: true,
  },
  {
    code: "pants-06",
    name: "연청바지",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-06.svg",
    sortOrder: 6,
    isActive: true,
  },
  {
    code: "pants-07",
    name: "크림진",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-07.svg",
    sortOrder: 7,
    isActive: true,
  },
  {
    code: "pants-08",
    name: "조거팬츠",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-08.svg",
    sortOrder: 8,
    isActive: true,
  },
  {
    code: "pants-09",
    name: "트레이닝 팬츠",
    category: "pants",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/pants/pants-09.svg",
    sortOrder: 9,
    isActive: true,
  },
  {
    code: "pants-10",
    name: "슬랙스 - 블랙",
    category: "pants",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/pants/pants-10.svg",
    sortOrder: 10,
    isActive: true,
  },
  {
    code: "pants-11",
    name: "슬랙스 - 베이지",
    category: "pants",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/pants/pants-11.svg",
    sortOrder: 11,
    isActive: true,
  },
  // 액세서리
  {
    code: "accessory-01",
    name: "수영모",
    category: "accessory",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/accessory/accessory-01.svg",
    sortOrder: 1,
    isActive: true,
  },
  {
    code: "accessory-02",
    name: "면도기",
    category: "accessory",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/accessory/accessory-02.svg",
    sortOrder: 2,
    isActive: true,
  },
  {
    code: "accessory-03",
    name: "로락스 시계",
    category: "accessory",
    price: 220,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/accessory/accessory-03.svg",
    sortOrder: 3,
    isActive: true,
  },
  {
    code: "accessory-04",
    name: "사과워치",
    category: "accessory",
    price: 120,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/accessory/accessory-04.svg",
    sortOrder: 4,
    isActive: true,
  },
  // 신발
  {
    code: "shoes-01",
    name: "고무신",
    category: "shoes",
    price: 20,
    requiredLevel: 3,
    imgUrl: "/images/poor-items/shoes/shoes-01.svg",
    sortOrder: 1,
    isActive: true,
  },
  {
    code: "shoes-02",
    name: "구멍난 운동화",
    category: "shoes",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/shoes/shoes-02.svg",
    sortOrder: 2,
    isActive: true,
  },
  {
    code: "shoes-03",
    name: "너덜너덜 슬리퍼",
    category: "shoes",
    price: 20,
    requiredLevel: 4,
    imgUrl: "/images/poor-items/shoes/shoes-03.svg",
    sortOrder: 3,
    isActive: true,
  },
  {
    code: "shoes-04",
    name: "닥터마팅",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-04.svg",
    sortOrder: 4,
    isActive: true,
  },
  {
    code: "shoes-05",
    name: "닥터마팅",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-05.svg",
    sortOrder: 5,
    isActive: true,
  },
  {
    code: "shoes-06",
    name: "닥터마팅",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-06.svg",
    sortOrder: 6,
    isActive: true,
  },
  {
    code: "shoes-07",
    name: "방스 단화",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-07.svg",
    sortOrder: 7,
    isActive: true,
  },
  {
    code: "shoes-08",
    name: "방스 단화",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-08.svg",
    sortOrder: 8,
    isActive: true,
  },
  {
    code: "shoes-09",
    name: "컹버스",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-09.svg",
    sortOrder: 9,
    isActive: true,
  },
  {
    code: "shoes-10",
    name: "에어포숙",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-10.svg",
    sortOrder: 10,
    isActive: true,
  },
  {
    code: "shoes-11",
    name: "된장포숙",
    category: "shoes",
    price: 40,
    requiredLevel: 5,
    imgUrl: "/images/poor-items/shoes/shoes-11.svg",
    sortOrder: 11,
    isActive: true,
  },
  {
    code: "shoes-12",
    name: "조단",
    category: "shoes",
    price: 70,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/shoes/shoes-12.svg",
    sortOrder: 12,
    isActive: true,
  },
  {
    code: "shoes-13",
    name: "독일군 스니커즈",
    category: "shoes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/shoes/shoes-13.svg",
    sortOrder: 13,
    isActive: true,
  },
  {
    code: "shoes-14",
    name: "구두",
    category: "shoes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/shoes/shoes-14.svg",
    sortOrder: 14,
    isActive: true,
  },
  {
    code: "shoes-15",
    name: "구두",
    category: "shoes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/shoes/shoes-15.svg",
    sortOrder: 15,
    isActive: true,
  },
  {
    code: "shoes-16",
    name: "구두",
    category: "shoes",
    price: 60,
    requiredLevel: 6,
    imgUrl: "/images/poor-items/shoes/shoes-16.svg",
    sortOrder: 16,
    isActive: true,
  },
  // 코스튬
  {
    code: "setup-01",
    name: "의사 거지",
    category: "setup",
    price: 20,
    requiredLevel: 7,
    imgUrl: "/images/poor-items/setup/setup-01.svg",
    sortOrder: 1,
    isActive: true,
  },
  {
    code: "setup-02",
    name: "우주인 거지",
    category: "setup",
    price: 20,
    requiredLevel: 8,
    imgUrl: "/images/poor-items/setup/setup-02.svg",
    sortOrder: 2,
    isActive: true,
  },
  {
    code: "setup-03",
    name: "산타 거지",
    category: "setup",
    price: 20,
    requiredLevel: 9,
    imgUrl: "/images/poor-items/setup/setup-03.svg",
    sortOrder: 3,
    isActive: true,
  },
  {
    code: "setup-04",
    name: "석유왕",
    category: "setup",
    price: 20,
    requiredLevel: 10,
    imgUrl: "/images/poor-items/setup/setup-04.svg",
    sortOrder: 4,
    isActive: true,
  },
];

async function main() {
  await prisma.ledgerItem.deleteMany();
  await prisma.ledger.deleteMany();
  await prisma.poorItemTransaction.deleteMany();
  await prisma.userPoorItem.deleteMany();
  await prisma.poorItem.deleteMany();
  await prisma.user.deleteMany();

  const hashedPassword = await bcrypt.hash("test1234", 12);

  const user = await prisma.user.create({
    data: {
      email: "test@example.com",
      password: hashedPassword,
      poorName: "테스트푸어",
      level: 5,
      points: 150,
      ledger: {
        create: {
          name: "테스트푸어의 가계부",
        },
      },
    },
  });

  const items: Prisma.LedgerItemCreateManyInput[] = seedData.map((item) => ({
    userId: user.id,
    name: item.name,
    type: item.type,
    category: item.category,
    amount: item.amount,
    date: new Date(item.date),
  }));

  const poorItemResult = await prisma.poorItem.createMany({ data: poorItems });
  const seededPoorItems = await prisma.poorItem.findMany({
    where: {
      code: {
        in: [...SEEDED_OWNED_POOR_ITEM_CODES],
      },
    },
    select: {
      id: true,
      code: true,
      price: true,
    },
  });

  await prisma.userPoorItem.createMany({
    data: seededPoorItems.map((poorItem) => ({
      userId: user.id,
      poorItemId: poorItem.id,
      equipped: SEEDED_EQUIPPED_POOR_ITEM_CODES.has(poorItem.code),
    })),
  });

  await prisma.poorItemTransaction.createMany({
    data: seededPoorItems.map((poorItem) => ({
      userId: user.id,
      poorItemId: poorItem.id,
      type: "purchase",
      pointAmount: -poorItem.price,
    })),
  });

  const result = await prisma.ledgerItem.createMany({ data: items });
  console.log(`Seeded user: ${user.email} (password: test1234)`);
  console.log(`Seeded ${poorItemResult.count} poor items`);
  console.log(`Seeded ${seededPoorItems.length} owned poor items`);
  console.log(`Seeded ${result.count} ledger items`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
